version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: project_postgres
    restart: always
    environment:
      POSTGRES_USER: rexileer
      POSTGRES_PASSWORD: 0528
      POSTGRES_DB: ollamatg
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
